# Generated by Django 5.1.3 on 2024-12-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('age', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('joinIngdate', models.DateField()),
                ('qualification', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=255)),
            ],
        ),
    ]
